apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-inventory-api/v0.1.2/config/crd/bases/multicluster.x-k8s.io_clusterprofiles.yaml
- ./clusterprofile-controller
