version: "2"

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports
